In [2]:
for i in range(0,4):
    for j in range(0,4):
        if(i+j>=3):
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()
            


      * 
    * * 
  * * * 
* * * * 


In [1]:
name=input("enter name:")
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end=" ")
    print()

enter name:pragathi
p 
r r 
a a a 
g g g g 
a a a a a 
t t t t t t 
h h h h h h h 
i i i i i i i i 


In [5]:
rec={}
n=int(input("enter number of students"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
print("name of the student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter number of students5
enter student name:abc
enter % marks of student85
enter student name:pqr
enter % marks of student83
enter student name:qwe
enter % marks of student78
enter student name:pra
enter % marks of student97
enter student name:avx
enter % marks of student97
name of the student 	 % of marks
	 abc 		 85
	 pqr 		 83
	 qwe 		 78
	 pra 		 97
	 avx 		 97


In [6]:
d={100:"abc",200:"pqr",300:"xyz"}
print(d)

{100: 'abc', 200: 'pqr', 300: 'xyz'}


In [7]:
d.clear()

In [8]:
print(d)

{}


In [9]:
del d

In [10]:
print(d)

NameError: name 'd' is not defined

In [11]:
d={100:"abc",200:"pqr",300:"xyz"}
len(d)

3

In [12]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any word:hello
h occure 1 times
e occure 1 times
l occure 2 times
o occure 1 times


In [1]:
word=input("enter any word:")
d={}
vowels={'a','e','i','o','u'}
for x in word:
     if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():    
    print(k,"occure",v,"times")
        

enter any word:abcdef
a occure 1 times
e occure 1 times


In [2]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [3]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [4]:
print(n.index(5))

4


In [5]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


list1=[1,2,3,"hello"]
list2=[4,5,6,"India"]
list1.extend(list2)
print(list1)

####remove

### remove

In [5]:
n1=[1,2,3,4]
print(n1)

[1, 2, 3, 4]


In [6]:
n1.pop()

4

In [9]:
n.reverse()
print(n)

[4, 3, 2, 888, 1]


In [10]:
names=["nireesha","hariprasad","iona","poorvika"]
names.sort()
print(names)

['hariprasad', 'iona', 'nireesha', 'poorvika']


In [11]:
names=["nireesha","hariprasad","iona","poorvika",5,7,1,2]
names.sort()
print(names)

TypeError: '<' not supported between instances of 'int' and 'str'

In [12]:
names=["nireesha","hariprasad","iona","poorvika"]
names.sort(reverse=True)
print(names)


['poorvika', 'nireesha', 'iona', 'hariprasad']


In [13]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [14]:
x=[10,20,30,40]
y=x                             #copy by reference
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [15]:
x=[10,20,30,40]
y=x.copy()                            #copy by value
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [16]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [17]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [20]:
x=["MITE","MANGALORE","NITTE"]
y=["MITE","MANGALORE","NITTE"]
x==y
x!=y
z=["MITE","MANGALORE","NITTE"]
x==z

True

In [21]:
M=[10,20,30,40,[50,60,70]]
M[3]

40

In [22]:
M[4][1]

60

In [23]:
M.clear()

In [24]:
n=[1,2,3,4]
print(4 in n)

True


In [25]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [26]:
words=["Mite","Mysore","Pragathi"]
l=[w[0] for w in words]
print(l)

['M', 'M', 'P']


In [28]:
def isprime(m):
    for i in range(2,m):
        if(m%i == 0):
            return False
    return True
m=int(input())
isprime(m)

    

3


True

In [29]:
def times2(var):
    return var*2

seq=[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [33]:
seq=[1,2,3,4,5]
#lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [34]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [35]:
import numpy as np

In [36]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [38]:
import numpy as np

In [39]:
import pandas as pd

In [40]:
import numpy as np


In [41]:
my_list=[1,2,3]

In [42]:
my_list

[1, 2, 3]

In [43]:
np.array(my_list)

array([1, 2, 3])

In [44]:
my_matrix=([1,2,3],[4,5,6],[7,8,9])

In [46]:
my_matrix

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [47]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [56]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.random.rand(2)

array([0.42082852, 0.56140868])

In [59]:
np.random.rand(5,5)

array([[0.47208477, 0.91638672, 0.61243625, 0.84690446, 0.24116501],
       [0.13463761, 0.09650682, 0.04962251, 0.61583365, 0.31926059],
       [0.87518536, 0.79418894, 0.54669814, 0.0315812 , 0.80058681],
       [0.01697935, 0.92469185, 0.23742543, 0.4795829 , 0.26264118],
       [0.09931699, 0.29839164, 0.80961408, 0.35300698, 0.90977448]])

In [60]:
np.random.randn(5,5)

array([[ 1.41843075, -0.74055512, -1.31440513,  1.27793325,  1.13872018],
       [-0.04571987,  1.64175515,  0.3895138 , -0.47376397,  0.47602765],
       [ 0.06712868,  0.88326014,  1.69667091,  0.4966966 ,  1.50798936],
       [ 3.35102013,  1.27193342,  0.88761234, -2.09344554,  1.20743047],
       [ 0.73901317, -1.12992765,  0.22627924,  0.90098822, -1.07418391]])

In [61]:
np.random.randint(1,100,100)

array([ 3, 49, 96, 23,  7, 43, 78, 90, 43, 82,  1, 90, 39, 82, 21, 27, 67,
       76, 48, 56, 42, 97, 51, 23, 48, 41, 14, 43, 89, 96, 92, 49, 99, 41,
       27, 16, 92, 99, 15,  7, 83, 84, 82, 59, 71, 32, 76, 52, 51, 27, 21,
       18, 67, 78, 73, 30, 20, 73, 54, 67, 19, 75, 98, 57, 17, 47, 30, 20,
       57, 35, 91, 73, 34, 28, 12,  7, 75, 15, 47, 88, 35, 36, 93, 68, 71,
       16, 56, 24, 85, 42, 42, 92, 24, 98, 55, 73, 45, 66, 57, 99])

In [62]:
ar=np.random.randint(1,100,100)

In [63]:
ar

array([ 9,  6, 21, 95, 19, 72, 17, 98, 36, 91, 50, 45, 77, 83, 30, 77, 72,
        6, 62, 62, 32, 86, 68, 49, 22, 46, 96, 68, 19, 80, 76, 38, 19, 46,
       94, 48, 50, 13, 80, 14, 90, 91, 71, 15,  6, 94, 44, 13, 22, 52, 14,
        6, 18, 55, 65, 65, 72, 89, 94, 44, 10, 86, 71, 34, 76, 30, 58, 71,
       82, 93, 37, 28, 56, 73, 26, 66, 27,  9, 75, 79, 46, 19, 44,  3, 20,
       63, 35, 30, 18,  9, 27, 39,  7, 77, 15, 12, 15,  9, 13, 69])

In [65]:
arr=np.arange(25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
runarr=np.random.randint(0,50,10)

In [68]:
runarr

array([32, 40, 35, 27,  8, 18,  3, 31, 24, 14])

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
runarr.max()

40

In [71]:
runarr.argmax()

1

In [72]:
runarr.min()

3

In [73]:
runarr.argmin()

6

In [74]:
arr.shape

(25,)

In [75]:
arr.reshape(25,1).shape

(25, 1)

In [76]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [77]:
arr.dtype

dtype('int32')

In [78]:
arr=np.arange(0,10)

In [79]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [81]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr/arr

C:\Users\User1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
1/arr

C:\Users\User1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
np.log(arr)

C:\Users\User1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [87]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [89]:
arr=np.arange(0,11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[8]

8

In [92]:
arr[1:5]

array([1, 2, 3, 4])

In [93]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [94]:
arr[0:5]=100

In [95]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
arr=np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [99]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr=np.arange(0,10)

In [102]:
np.ones(10)=5

SyntaxError: can't assign to function call (<ipython-input-102-a013af7be79d>, line 1)

In [103]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.arange(0,10,2)

NameError: name 'np' is not defined

In [9]:
import numpy as np

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10,80,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [105]:
ar1=np.ones(10)

In [107]:
ar1[0:10]=5

In [108]:
ar1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
ar2=np.arange(0,9)

In [22]:
ar2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.random.randn(25)

array([ 0.6293681 , -0.79813121, -2.04511116, -0.37974118,  0.65981419,
       -0.2884822 , -0.34003757,  0.94962099, -0.32459724,  0.55953373,
       -0.88598664, -0.16540435,  0.31617068, -0.4266097 ,  1.09204397,
       -0.42248106, -0.01294621,  0.43087291, -1.16131186,  1.00397018,
        1.28791842,  0.16043013,  0.93136581, -0.39329531, -0.90886664])

In [15]:
ar3=np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
import numpy as np


In [26]:
ar3=np.arange(1,26)

In [27]:
ar3.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
ar4=np.ones(10)

In [32]:
ar4[0:10]=5

In [33]:
print(ar4)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
